"""Cambio campo delete_at de tokenrefresh a nullable=true

Revision ID: 559998f59a15
Revises: f1f20efeb4d9
Create Date: 2025-07-15 11:53:00.768565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559998f59a15'
down_revision: Union[str, Sequence[str], None] = 'f1f20efeb4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
