"""Agregar expiración y estado a token

Revision ID: 8abca4d77521
Revises: 3b9fbe1fb7a3
Create Date: 2025-07-11 16:39:51.230944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abca4d77521'
down_revision: Union[str, Sequence[str], None] = '3b9fbe1fb7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokenrefresh', sa.Column('expiration', sa.DateTime(), nullable=False))
    op.add_column('tokenrefresh', sa.Column('state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokenrefresh', 'state')
    op.drop_column('tokenrefresh', 'expiration')
    # ### end Alembic commands ###
