"""Cambio campo delete_at de tokenrefresh a nullable=true

Revision ID: f1f20efeb4d9
Revises: 8abca4d77521
Create Date: 2025-07-15 11:52:17.287011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1f20efeb4d9'
down_revision: Union[str, Sequence[str], None] = '8abca4d77521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokenrefresh', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokenrefresh', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###

